spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bidingsystem?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 162.14.71.2  #????????
    port: 6379      #????????
    password: 123456
    client-type: lettuce
    jedis:
      pool:
        max-active: 16
server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      table-prefix: tab_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


