spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bidingsystem?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1  #????????
    port: 6379      #????????
#    password: 123456
    client-type: lettuce
    timeout: 10000
    jedis:
      pool:
        max-active: 16
  servlet:
    multipart:
      max-file-size: 500MB  #单个数据大小
      max-request-size: 1024MB #总数据大小
server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      table-prefix: tab_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
cos:
  baseUrl: https://zhangbo-1306119450.cos.ap-chengdu.myqcloud.com
  accessKey: AKID9Jya44zpfVJiz8JLI9sSpW6Wmy7AA6vb
  secretKey: oRmvhMxQmz6SddS2Wq2OwLZcanvvpXAb
  regionName: ap-chengdu
  bucketName: zhangbo-1306119450
  folderPrefix: /files


